<%@ Page Title="" Language="C#" MasterPageFile="~/AdminPanel/Admin.Master" AutoEventWireup="true" CodeBehind="UserDetails.aspx.cs" Inherits="VaccineMangmentApp.AdminPanel.UserDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mybody" runat="server">
    <div class="container-fluid">
        <div class="row">
            <form id="form1" runat="server" class="frmalg">
                <div class="row">
                    <li class="nav-item accordion-button">
                        <a class="nav-link" href="AddUser.aspx">Add User</a>
                    </li>
                    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderStyle="Solid" CellPadding="4" CssClass="form-control" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" DataKeyNames="ID">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <Columns>
                            <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                            <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                            <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                            <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
                            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                            <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                            <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" SortExpression="MobileNo" />
                            <asp:CheckBoxField DataField="IsAdmin" HeaderText="IsAdmin" SortExpression="IsAdmin" />
                            <asp:BoundField DataField="UserID" HeaderText="UserID" SortExpression="UserID" />
                            <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                        </Columns>
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:VaccineMasterConnectionString %>" SelectCommand="SELECT [FirstName], [LastName], [DOB], [Age], [Password], [Address], [City], [MobileNo], [IsAdmin], [UserID], [ID] FROM [UserMaster]" DeleteCommand="DELETE FROM [UserMaster] WHERE [ID] = @ID" InsertCommand="INSERT INTO [UserMaster] ([FirstName], [LastName], [DOB], [Age], [Password], [Address], [City], [MobileNo], [IsAdmin], [UserID]) VALUES (@FirstName, @LastName, @DOB, @Age, @Password, @Address, @City, @MobileNo, @IsAdmin, @UserID)" UpdateCommand="UPDATE [UserMaster] SET [FirstName] = @FirstName, [LastName] = @LastName, [DOB] = @DOB, [Age] = @Age, [Password] = @Password, [Address] = @Address, [City] = @City, [MobileNo] = @MobileNo, [IsAdmin] = @IsAdmin, [UserID] = @UserID WHERE [ID] = @ID">
                        <DeleteParameters>
                            <asp:Parameter Name="ID" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="FirstName" Type="String" />
                            <asp:Parameter Name="LastName" Type="String" />
                            <asp:Parameter DbType="Date" Name="DOB" />
                            <asp:Parameter Name="Age" Type="Int32" />
                            <asp:Parameter Name="Password" Type="String" />
                            <asp:Parameter Name="Address" Type="String" />
                            <asp:Parameter Name="City" Type="String" />
                            <asp:Parameter Name="MobileNo" Type="String" />
                            <asp:Parameter Name="IsAdmin" Type="Boolean" />
                            <asp:Parameter Name="UserID" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="FirstName" Type="String" />
                            <asp:Parameter Name="LastName" Type="String" />
                            <asp:Parameter DbType="Date" Name="DOB" />
                            <asp:Parameter Name="Age" Type="Int32" />
                            <asp:Parameter Name="Password" Type="String" />
                            <asp:Parameter Name="Address" Type="String" />
                            <asp:Parameter Name="City" Type="String" />
                            <asp:Parameter Name="MobileNo" Type="String" />
                            <asp:Parameter Name="IsAdmin" Type="Boolean" />
                            <asp:Parameter Name="UserID" Type="Int32" />
                            <asp:Parameter Name="ID" Type="Int32" />
                        </UpdateParameters>
                        </asp:SqlDataSource>

                </div>
            </form>
        </div>
    </div>
</asp:Content>