//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineMangmentApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSlotMaster
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public int VaacineID { get; set; }
        public string CenterName { get; set; }
        public string VacineName { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int AvailabeVaccine { get; set; }
        public int AgeLimit { get; set; }
    
        public virtual VaccineCenterMaster VaccineCenterMaster { get; set; }
        public virtual VaccineMaster VaccineMaster { get; set; }
    }
}
