//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineMangmentApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaccineMasterEntities1 : DbContext
    {
        public VaccineMasterEntities1()
            : base("name=VaccineMasterEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingSlotMaster> BookingSlotMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<VaccineBookingMaster> VaccineBookingMasters { get; set; }
        public virtual DbSet<VaccineCenterMaster> VaccineCenterMasters { get; set; }
        public virtual DbSet<VaccineMaster> VaccineMasters { get; set; }
    }
}
