//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineMangmentApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineBookingMaster
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public int VaccineID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string VaccineName { get; set; }
        public string City { get; set; }
        public string CenterName { get; set; }
        public System.DateTime BookedDate { get; set; }
        public string Startus { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual VaccineCenterMaster VaccineCenterMaster { get; set; }
        public virtual VaccineMaster VaccineMaster { get; set; }
    }
}
